apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-init-config
  namespace: jenkins
data:
  init.groovy: |
    #!groovy
    import jenkins.model.*
    import hudson.security.*
    import jenkins.install.InstallState
    
    def instance = Jenkins.getInstance()
    
    // 跳过安装向导，直接设置安全配置
    if (!instance.installState.isSetupComplete()) {
      println "--> Setting up Jenkins security configuration"
      
      // 创建安全域 - 允许匿名读取，但需要登录才能执行操作
      def strategy = new GlobalMatrixAuthorizationStrategy()
      
      // 给匿名用户只读权限
      strategy.add(Jenkins.READ, 'anonymous')
      
      // 给已验证用户所有权限
      strategy.add(Jenkins.ADMINISTER, 'authenticated')
      
      instance.setAuthorizationStrategy(strategy)
      
      // 禁用安全域，允许任何人访问（生产环境不推荐）
      // 或者使用基本安全域
      def realm = new HudsonPrivateSecurityRealm(false)
      realm.createAccount("admin", "admin123")
      instance.setSecurityRealm(realm)
      
      // 设置安装状态为完成
      instance.setInstallState(InstallState.INITIAL_SETUP_COMPLETED)
      
      // 保存配置
      instance.save()
      
      println "--> Jenkins security setup completed"
      println "--> Default admin credentials: admin / admin123"
    }