apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      serviceAccountName: jenkins  # 确保使用正确的 ServiceAccount
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: JAVA_OPTS
          value: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
        - name: JENKINS_OPTS
          value: "--argumentsRealm.passwd.admin=admin123 --argumentsRealm.roles.admin=admin"
        resources:
          requests:
            memory: "256Mi"
            cpu: "512m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-init-script
          mountPath: /usr/share/jenkins/ref/init.groovy.d/01-init.groovy
          subPath: init.groovy
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-master-pvc
      - name: jenkins-init-script
        configMap:
          name: jenkins-init-config
          defaultMode: 0644