apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-init-config
  namespace: jenkins
data:
  init.groovy: |
    #!groovy
    import jenkins.model.*
    import hudson.security.*
    
    def instance = Jenkins.getInstance()
    
    // 只在初次安装时设置
    if (!instance.isInstallStateSet()) {
      println "--> Setting up initial security"
      
      // 创建本地用户数据库
      def hudsonRealm = new HudsonPrivateSecurityRealm(false)
      hudsonRealm.createAccount("admin", "admin123")
      instance.setSecurityRealm(hudsonRealm)
      
      // 设置授权策略
      def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
      strategy.setAllowAnonymousRead(false)
      instance.setAuthorizationStrategy(strategy)
      
      // 标记安装完成
      instance.setInstallState(InstallState.INITIAL_SETUP_COMPLETED)
      
      // 保存配置
      instance.save()
      
      println "--> Initial security setup completed"
    }