apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      serviceAccountName: jenkins
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      initContainers:
      - name: install-aws-cli
        image: alpine:3.18
        command:
        - sh
        - -c
        - |
          echo "AWS CLI will be installed in main container via volume"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: JAVA_OPTS
          value: "-Djava.awt.headless=true -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"
        # 添加安装脚本到启动前
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - |
                # 在后台安装 AWS CLI，不影响 Jenkins 启动
                (apt-get update && \
                apt-get install -y curl unzip && \
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
                unzip awscliv2.zip && \
                ./aws/install && \
                rm -rf awscliv2.zip aws/ && \
                echo "AWS CLI installed successfully") &
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: disable-csrf-script
          mountPath: /usr/share/jenkins/ref/init.groovy.d/disable-csrf.groovy
          subPath: disable-csrf.groovy
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-master-pvc
      - name: disable-csrf-script
        configMap:
          name: jenkins-disable-csrf
          defaultMode: 0644