apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jnlp
        image: jenkins/inbound-agent:jdk11
        env:
        - name: JENKINS_URL
          value: "http://jenkins-master.jenkins:8080"
        - name: JENKINS_SECRET
          value: ""
        - name: JENKINS_AGENT_NAME
          value: "eks-agent"
        - name: JENKINS_AGENT_WORKDIR
          value: "/home/jenkins/agent"
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for Jenkins Master to be ready..."
          sleep 60  # 简单等待
          echo "Starting Jenkins agent..."
          java -jar /usr/share/jenkins/agent.jar \
            -url http://jenkins-master.jenkins:8080 \
            -workDir /home/jenkins/agent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"